language: objective-c
osx_image: xcode8.2
xcode_scheme: CI-Comparisons
xcode_project: CI-Comparisons.xcodeproj
xcode_sdk: iphonesimulator
before_install:
  - brew update
  - brew reinstall xctool
script: xctool -project CI-Comparisons/CI-Comparisons.xcodeproj -scheme CI-Comparisons -sdk iphonesimulator -configuration Debug run-tests
