language: swift
osx_image: xcode8.2
xcode_sdk: iphonesimulator10.2
xcode_scheme: CI-Comparisons
xcode_project: ./CI-Comparisons/CI-Comparisons.xcodeproj 
before_install:
  - brew update
  - brew reinstall xctool
